[2022-09-29 13:28:04,870] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-setl1.spark_job_setl1 manual__2022-09-29T13:28:04.611161+00:00 [queued]>
[2022-09-29 13:28:04,877] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-setl1.spark_job_setl1 manual__2022-09-29T13:28:04.611161+00:00 [queued]>
[2022-09-29 13:28:04,878] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-29 13:28:04,878] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-09-29 13:28:04,878] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-29 13:28:04,887] {taskinstance.py:1259} INFO - Executing <Task(SparkSubmitOperator): spark_job_setl1> on 2022-09-29 13:28:04.611161+00:00
[2022-09-29 13:28:04,894] {standard_task_runner.py:52} INFO - Started process 2209 to run task
[2022-09-29 13:28:04,896] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'spark-setl1', 'spark_job_setl1', 'manual__2022-09-29T13:28:04.611161+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/spark-setl-scala1.py', '--cfg-path', '/tmp/tmpta3oub4o', '--error-file', '/tmp/tmp2vbilua3']
[2022-09-29 13:28:04,897] {standard_task_runner.py:77} INFO - Job 35: Subtask spark_job_setl1
[2022-09-29 13:28:04,944] {logging_mixin.py:109} INFO - Running <TaskInstance: spark-setl1.spark_job_setl1 manual__2022-09-29T13:28:04.611161+00:00 [running]> on host 4d693a43fffb
[2022-09-29 13:28:05,044] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***admin@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark-setl1
AIRFLOW_CTX_TASK_ID=spark_job_setl1
AIRFLOW_CTX_EXECUTION_DATE=2022-09-29T13:28:04.611161+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-29T13:28:04.611161+00:00
[2022-09-29 13:28:05,059] {base.py:79} INFO - Using connection to: id: spark_default2. Host: spark://spark, Port: 36453, Schema: , Login: spark_default, Password: ***, extra: {'deploy-mode': 'client'}
[2022-09-29 13:28:05,060] {spark_submit.py:334} INFO - Spark-Submit cmd: spark-submit --master spark://spark:36453 --jars /home/hoaln/work/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar --class scala.Job_s2t_AddTagVideo --deploy-mode client /home/hoaln/work/jars/setl_2.12-1.0.0-SNAPSHOT.jar
[2022-09-29 13:28:06,966] {spark_submit.py:485} INFO - 22/09/29 13:28:06 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2022-09-29 13:28:07,094] {spark_submit.py:485} INFO - 22/09/29 13:28:07 WARN DependencyUtils: Local jar /home/hoaln/work/jars/setl_2.12-1.0.0-SNAPSHOT.jar does not exist, skipping.
[2022-09-29 13:28:07,094] {spark_submit.py:485} INFO - 22/09/29 13:28:07 WARN DependencyUtils: Local jar /home/hoaln/work/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar does not exist, skipping.
[2022-09-29 13:28:07,094] {spark_submit.py:485} INFO - Error: Failed to load class scala.Job_s2t_AddTagVideo.
[2022-09-29 13:28:07,098] {spark_submit.py:485} INFO - 22/09/29 13:28:07 INFO ShutdownHookManager: Shutdown hook called
[2022-09-29 13:28:07,098] {spark_submit.py:485} INFO - 22/09/29 13:28:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-9c95e8d2-8b39-4477-8b8f-248df0c3bfca
[2022-09-29 13:28:07,158] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 417, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:36453 --jars /home/hoaln/work/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar --class scala.Job_s2t_AddTagVideo --deploy-mode client /home/hoaln/work/jars/setl_2.12-1.0.0-SNAPSHOT.jar. Error code is: 101.
[2022-09-29 13:28:07,164] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=spark-setl1, task_id=spark_job_setl1, execution_date=20220929T132804, start_date=20220929T132804, end_date=20220929T132807
[2022-09-29 13:28:07,173] {standard_task_runner.py:92} ERROR - Failed to execute job 35 for task spark_job_setl1
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 417, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:36453 --jars /home/hoaln/work/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar --class scala.Job_s2t_AddTagVideo --deploy-mode client /home/hoaln/work/jars/setl_2.12-1.0.0-SNAPSHOT.jar. Error code is: 101.
[2022-09-29 13:28:07,202] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-29 13:28:07,241] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
