[2022-09-29 13:23:48,617] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-setl1.spark_job_setl1 manual__2022-09-29T13:23:47.576832+00:00 [queued]>
[2022-09-29 13:23:48,624] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-setl1.spark_job_setl1 manual__2022-09-29T13:23:47.576832+00:00 [queued]>
[2022-09-29 13:23:48,624] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-29 13:23:48,624] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-09-29 13:23:48,625] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-29 13:23:48,631] {taskinstance.py:1259} INFO - Executing <Task(SparkSubmitOperator): spark_job_setl1> on 2022-09-29 13:23:47.576832+00:00
[2022-09-29 13:23:48,636] {standard_task_runner.py:52} INFO - Started process 1688 to run task
[2022-09-29 13:23:48,638] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'spark-setl1', 'spark_job_setl1', 'manual__2022-09-29T13:23:47.576832+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/spark-setl-scala1.py', '--cfg-path', '/tmp/tmpcl6pjybd', '--error-file', '/tmp/tmpk8c79j0g']
[2022-09-29 13:23:48,638] {standard_task_runner.py:77} INFO - Job 29: Subtask spark_job_setl1
[2022-09-29 13:23:48,670] {logging_mixin.py:109} INFO - Running <TaskInstance: spark-setl1.spark_job_setl1 manual__2022-09-29T13:23:47.576832+00:00 [running]> on host 4d693a43fffb
[2022-09-29 13:23:48,706] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***admin@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark-setl1
AIRFLOW_CTX_TASK_ID=spark_job_setl1
AIRFLOW_CTX_EXECUTION_DATE=2022-09-29T13:23:47.576832+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-29T13:23:47.576832+00:00
[2022-09-29 13:23:48,712] {base.py:79} INFO - Using connection to: id: spark_default2. Host: spark://172.22.0.2, Port: 36453, Schema: , Login: spark_default, Password: ***, extra: {'deploy-mode': 'master'}
[2022-09-29 13:23:48,713] {spark_submit.py:334} INFO - Spark-Submit cmd: spark-submit --master spark://172.22.0.2:36453 --jars /home/hoaln/work/git_clone/clone_project/***_repo/***-spark/spark/resources/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar --class scala.Job_s2t_AddTagVideo --deploy-mode master /home/hoaln/work/git_clone/clone_project/***_repo/***-spark/spark/resources/jars/setl_2.12-1.0.0-SNAPSHOT.jar
[2022-09-29 13:23:49,938] {spark_submit.py:485} INFO - Exception in thread "main" org.apache.spark.SparkException: --deploy-mode must be either "client" or "cluster"
[2022-09-29 13:23:49,938] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2022-09-29 13:23:49,938] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmitArguments.handle(SparkSubmitArguments.scala:348)
[2022-09-29 13:23:49,938] {spark_submit.py:485} INFO - at org.apache.spark.launcher.SparkSubmitOptionParser.parse(SparkSubmitOptionParser.java:163)
[2022-09-29 13:23:49,938] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:108)
[2022-09-29 13:23:49,938] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1029)
[2022-09-29 13:23:49,938] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1029)
[2022-09-29 13:23:49,938] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2022-09-29 13:23:49,938] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2022-09-29 13:23:49,938] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2022-09-29 13:23:49,938] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2022-09-29 13:23:49,967] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 417, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.22.0.2:36453 --jars /home/hoaln/work/git_clone/clone_project/***_repo/***-spark/spark/resources/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar --class scala.Job_s2t_AddTagVideo --deploy-mode master /home/hoaln/work/git_clone/clone_project/***_repo/***-spark/spark/resources/jars/setl_2.12-1.0.0-SNAPSHOT.jar. Error code is: 1.
[2022-09-29 13:23:49,974] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=spark-setl1, task_id=spark_job_setl1, execution_date=20220929T132347, start_date=20220929T132348, end_date=20220929T132349
[2022-09-29 13:23:49,987] {standard_task_runner.py:92} ERROR - Failed to execute job 29 for task spark_job_setl1
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 417, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.22.0.2:36453 --jars /home/hoaln/work/git_clone/clone_project/***_repo/***-spark/spark/resources/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar --class scala.Job_s2t_AddTagVideo --deploy-mode master /home/hoaln/work/git_clone/clone_project/***_repo/***-spark/spark/resources/jars/setl_2.12-1.0.0-SNAPSHOT.jar. Error code is: 1.
[2022-09-29 13:23:50,013] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-29 13:23:50,038] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
